openapi: 3.0.3

info:
  version: 0.0.1
  title: Waarborgfonds saneringskredieten
  description: |
paths:

  /api/mijn-fiatteer-uitbetaling-taken:
    get:
      tags:
        - fiatteer uitbetaling taken
      summary: Geeft een persoonlijke lijst van fiatteer uitbetaling taken.
      description: |
        Geeft een lijst van geclaimde taken. Wanneer de gebruiker geen taken heeft geclaimed dan worden de niet geclaimde taken met de hoogste prioriteit waarvoor de gebruiker geautoriseerd is getoond.
      operationId: GeefMijnFiatteerUitbetalingTakenV1
      parameters:
        - $ref: "../../../data-dictionary/parameters/limit.yml"
        - $ref: "../../../data-dictionary/parameters/offset.yml"
      responses:
        200:          
          description: OK
          content:
            application/json:
              schema:
                $ref: "../../../data-dictionary/responses/mijn_taken.yml"
        401:
          $ref: "../../../data-dictionary/responses/types/401.yml"
        403:
          $ref: "../../../data-dictionary/responses/types/403.yml"

  /api/fiatteer-uitbetaling-taken/{taak_id}:
    parameters:        
      - $ref: "../../../data-dictionary/parameters/taak_id.yml"
    get:
      tags:
        - fiatteer uitbetaling taken
      summary: Geeft een fiatteer uitbetaling taak.
      operationId: GeefFiatteerUitbetalingTaakV1
      responses:
        200:          
          description: OK
          content:
            application/json:
              schema:
                $ref: "../../../data-dictionary/responses/fiatteer_uitbetaling_taak.yml"
        400:
          $ref: "../../../data-dictionary/responses/types/400.yml"
        401:
          $ref: "../../../data-dictionary/responses/types/401.yml"
        403:
          $ref: "../../../data-dictionary/responses/types/403.yml"
        404:
          $ref: "../../../data-dictionary/responses/types/404.yml"  

  /api/fiatteer-uitbetaling-taken/{taak_id}/fiatteren:
    parameters:        
      - $ref: "../../../data-dictionary/parameters/taak_id.yml"
    put:
      tags:
        - fiatteer uitbetaling taken
      summary: Fiatteert de uitbetaling van de borgstelling goed.
      operationId: VoltooiFiatteerUitbetalingTaakMetFiatterenV1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "../../../data-dictionary/commands/fiatteer_uitbetaling.yml"
      responses:
        202:
          $ref: "../../../data-dictionary/responses/types/202.yml"
        400:
          $ref: "../../../data-dictionary/responses/types/400.yml"
        401:
          $ref: "../../../data-dictionary/responses/types/401.yml"
        403:
          $ref: "../../../data-dictionary/responses/types/403.yml"
        404:
          $ref: "../../../data-dictionary/responses/types/404.yml"

  /api/fiatteer-uitbetaling-taken/{taak_id}/afwijzen:
    parameters:        
      - $ref: "../../../data-dictionary/parameters/taak_id.yml"
    put:
      tags:
        - fiatteer uitbetaling taken
      summary: Wijst de uitbetaling van de borgstelling af.
      operationId: VoltooiFiatteerUitbetalingMetAfwijzenV1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "../../../data-dictionary/commands/wijs_uitbetaling_verzoek_af.yml"
      responses:
        202:
          $ref: "../../../data-dictionary/responses/types/202.yml"
        400:
          $ref: "../../../data-dictionary/responses/types/400.yml"
        401:
          $ref: "../../../data-dictionary/responses/types/401.yml"
        403:
          $ref: "../../../data-dictionary/responses/types/403.yml"
        404:
          $ref: "../../../data-dictionary/responses/types/404.yml"